In [ ]:
import pandas as pd
import numpy as np
from collections import Counter

In [ ]:
date_parser = lambda c: pd.to_datetime(c, format='%d/%m/%Y %H:%M:%S', errors='coerce')
data = pd.read_csv('ITSM_data.csv', parse_dates=['Open_Time','Reopen_Time','Close_Time','Resolved_Time'])

FileNotFoundError: ignored

In [ ]:
data.head(2)

CI_Name          CI_Cat              CI_Subcat        WBS Incident_ID  \
0  SUB000508  subapplication  Web Based Application  WBS000162   IM0000004   
1  WBA000124     application  Web Based Application  WBS000088   IM0000005   

   Status Impact Urgency  Priority  Unnamed: 9  ...         Reopen_Time  \
0  Closed      4       4       4.0    0.820967  ...                 NaT   
1  Closed      3       3       3.0    0.936566  ... 2013-02-12 12:31:02   

        Resolved_Time          Close_Time  Handle_Time_hrs  Closure_Code  \
0 2013-04-11 13:50:27 2013-04-11 13:51:17      3871,691111         Other   
1 2013-02-12 12:36:21 2013-02-12 12:36:25      4354,786389      Software   

  No_of_Related_Interactions Related_Interaction No_of_Related_Incidents  \
0                        1.0           SD0000007                     2.0   
1                        1.0           SD0000011                     1.0   

  No_of_Related_Changes Related_Change  
0                   NaN            NaN  
1                   NaN            NaN  

[2 rows x 26 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46606 entries, 0 to 46605
Data columns (total 26 columns):
CI_Name                       46606 non-null object
CI_Cat                        46495 non-null object
CI_Subcat                     46495 non-null object
WBS                           46606 non-null object
Incident_ID                   46606 non-null object
Status                        46606 non-null object
Impact                        46606 non-null object
Urgency                       46606 non-null object
Priority                      45226 non-null float64
Unnamed: 9                    46606 non-null float64
Category                      46606 non-null object
KB_number                     46606 non-null object
Alert_Status                  46606 non-null object
No_of_Reassignments           46605 non-null float64
Unnamed: 14                   46606 non-null int64
Open_Time                     46606 non-null datetime64[ns]
Reopen_Time                   2284 non-null datet

In [ ]:
Counter(data.No_of_Reassignments).most_common(20)

[(0.0, 27468),
 (1.0, 7268),
 (2.0, 5378),
 (3.0, 2191),
 (4.0, 1606),
 (5.0, 721),
 (6.0, 622),
 (7.0, 329),
 (8.0, 246),
 (9.0, 170),
 (10.0, 146),
 (11.0, 101),
 (13.0, 61),
 (12.0, 58),
 (14.0, 47),
 (15.0, 43),
 (17.0, 27),
 (16.0, 25),
 (18.0, 14),
 (21.0, 11)]

In [ ]:
data.No_of_Reassignments[2].dtype

dtype('float64')

In [ ]:
data.loc[data.No_of_Reassignments>3.0,'reassignment'] ='high'
data.loc[data.No_of_Reassignments<=3.0,'reassignment'] ='low'

In [ ]:
data.head()

CI_Name          CI_Cat              CI_Subcat        WBS Incident_ID  \
0  SUB000508  subapplication  Web Based Application  WBS000162   IM0000004   
1  WBA000124     application  Web Based Application  WBS000088   IM0000005   
2  DTA000024     application    Desktop Application  WBS000092   IM0000006   
3  WBA000124     application  Web Based Application  WBS000088   IM0000011   
4  WBA000124     application  Web Based Application  WBS000088   IM0000012   

   Status Impact Urgency  Priority  Unnamed: 9  ...       Resolved_Time  \
0  Closed      4       4       4.0    0.820967  ... 2013-04-11 13:50:27   
1  Closed      3       3       3.0    0.936566  ... 2013-02-12 12:36:21   
2  Closed     NS       3       NaN    0.069016  ... 2014-01-13 15:12:38   
3  Closed      4       4       4.0    0.936214  ... 2013-11-14 09:31:09   
4  Closed      4       4       4.0    0.062957  ... 2013-08-11 13:55:49   

           Close_Time Handle_Time_hrs                  Closure_Code  \
0 2013-04-11 13:51:17     3871,691111                         Other   
1 2013-02-12 12:36:25     4354,786389                      Software   
2 2014-01-13 15:13:11     4843,119444  No error - works as designed   
3 2013-11-14 09:31:24     43,21833333                Operator error   
4 2013-08-11 13:55:52     3383,903333                         Other   

   No_of_Related_Interactions Related_Interaction No_of_Related_Incidents  \
0                         1.0           SD0000007                     2.0   
1                         1.0           SD0000011                     1.0   
2                         1.0           SD0000017                     NaN   
3                         1.0           SD0000025                     NaN   
4                         1.0           SD0000029                     NaN   

  No_of_Related_Changes Related_Change reassignment  
0                   NaN            NaN         high  
1                   NaN            NaN         high  
2                   NaN            NaN          low  
3                   NaN            NaN         high  
4                   NaN            NaN          low  

[5 rows x 27 columns]

In [ ]:
Counter(data.reassignment)

Counter({'high': 4300, 'low': 42305, nan: 1})

In [ ]:
data = data[data.reassignment.isnull()==False]

In [ ]:
Counter(data.reassignment)

Counter({'high': 4300, 'low': 42305})

In [ ]:
selected = data.loc[:,['CI_Cat','CI_Subcat','WBS','Category','reassignment']]
selected.dropna(inplace=True)

In [ ]:
selected.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46494 entries, 0 to 46605
Data columns (total 5 columns):
CI_Cat          46494 non-null object
CI_Subcat       46494 non-null object
WBS             46494 non-null object
Category        46494 non-null object
reassignment    46494 non-null object
dtypes: object(5)
memory usage: 2.1+ MB


In [ ]:
X = selected.loc[:,['CI_Cat','CI_Subcat','WBS','Category']]
y = selected.reassignment


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
enc = LabelEncoder()
X.CI_Cat = enc.fit_transform(X.CI_Cat)
X.CI_Subcat = enc.fit_transform(X.CI_Subcat)
X.WBS = enc.fit_transform(X.WBS)
X.Category = enc.fit_transform(X.Category)

In [ ]:
X.shape

(46494, 4)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,stratify=y,random_state=0)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [ ]:
X_train = X_train.astype('float')

In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_train_smote, y_train_smote = smote.fit_sample(X_train,y_train)

In [ ]:
model=RandomForestClassifier()
model.fit(X_train_smote,y_train_smote)
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

/Users/ashokveda/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


[[ 676  397]
 [2733 7818]]
0.7307295251204404
              precision    recall  f1-score   support

        high       0.20      0.63      0.30      1073
         low       0.95      0.74      0.83     10551

    accuracy                           0.73     11624
   macro avg       0.57      0.69      0.57     11624
weighted avg       0.88      0.73      0.78     11624



### Trying one hot encoding for better efficiency

In [ ]:
selected = data.loc[:,['CI_Cat','CI_Subcat','WBS','Category','reassignment']]
selected.dropna(inplace=True)
X = selected.loc[:,['CI_Cat','CI_Subcat','WBS','Category']]
y = selected.reassignment
X = pd.get_dummies(X)

In [ ]:
X.shape

(46494, 351)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,stratify=y,random_state=0)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

In [ ]:
model=RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
accuracy_score(y_test,y_pred)

[[   7  666    0]
 [   3 9987   14]
 [   3  939    5]]


0.86020302821748107

[link text](https://)#### Not much improvement through one hot encoding